### ISSUE TITLE
チュートリアルにしたがってNode.js v17がインストールされると、yarn startでエラーになる

### ISSUE THREAD

**Issue by suin** [yytypescript/book#100]
- チュートリアルで[環境構築でbrew install nodeする](https://github.com/yytypescript/book/blob/c386e9b957a346ad85ff3b0cbd1f335294750072/docs/tutorials/setup.md#nodejs%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB)が、最近はv17が入るらしい。
- チュートリアルで[Reactのチュートリアルでyarn startするところがある](https://github.com/yytypescript/book/blob/c386e9b957a346ad85ff3b0cbd1f335294750072/docs/tutorials/react-like-button-tutorial.md#%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%82%92%E4%BD%9C%E3%82%8B)が、ここでv17だとエラーになるらしい。
- この問題が報告されたissue: #98 

## やること

- [x] v17環境で再現し、詳細を確認する。
- [ ] エラーが起きないような手順にする。

エラーが起きないようにするには、brew installでLTSを指定するようにするか、React側の問題もあるのでReactのチュートリアルを直すか、など考えられる

**Comment by t-yng** [comment]
Node.js v17 環境で `yarn start` を実行したら、エラーが発生した。👀

```sh
ヾ(*・ω・)ノ ~/workspace/react-tutorial/like-button  [ main ]
$ node -v

v17.0.1

ヾ(*・ω・)ノ ~/workspace/react-tutorial/like-button  [ main ]
$ yarn start
yarn run v1.22.17
$ react-scripts start
node:internal/modules/cjs/loader:488
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /Users/tomohiro/workspace/react-tutorial/like-button/node_modules/postcss-safe-parser/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:416:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:669:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/tomohiro/workspace/react-tutorial/like-button/node_modules/postcss-safe-parser/lib/safe-parser.js:1:17) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v17.0.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by t-yng** [comment]
該当のissueは↓を参照
ttps://github.com/facebook/create-react-app/issues/11565

やり取りを見る感じだと素直にv16を使うのが早そう

**Comment by t-yng** [comment]
`yarn.lock` をアップデートしてパッケージを再インストールしたら別のエラーが発生した。🥲

```sh
$ yarn start
yarn run v1.22.17
$ react-scripts start
ℹ ｢wds｣: Project is running at http://192.168.0.204/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /Users/tomohiro/workspace/react-tutorial/like-button/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...

/Users/tomohiro/workspace/react-tutorial/like-button/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/tomohiro/workspace/react-tutorial/like-button/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/tomohiro/workspace/react-tutorial/like-button/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/tomohiro/workspace/react-tutorial/like-button/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/tomohiro/workspace/react-tutorial/like-button/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/tomohiro/workspace/react-tutorial/like-button/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/tomohiro/workspace/react-tutorial/like-button/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/tomohiro/workspace/react-tutorial/like-button/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/tomohiro/workspace/react-tutorial/like-button/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by t-yng** [comment]
↑はOS依存のエラーっぽいが、解決策として実行時に `NODE_OPTIONS=--openssl-legacy-provider` を指定する必要がありそうだった。
https://github.com/webpack/webpack/issues/14532#issuecomment-947012063
